### ISSUE TITLE
A question and a glitch

### ISSUE THREAD

**Issue by Aetrnl94** [Luis-st/Forge-XBackpack#4]
Hi, I love using this mod, it make exploring so much more fun! I have a question and an issue: 
Question: With the enchanting table, are any book levels applied, or is it just the base level (no bookshelves); and if I'm standing near bookshelves, does that increase the enchant levels?
Issue: I noticed that if there's a bunch of stuff in the backpack, when I try and add new stuff it tends to put random items back in my inventory. I can then put those items in the backpack, but it really slows down the process. Any ways around that? 

Thanks!

Minecraft 1.19.4, Forge

**Comment by Luis-St** [comment]
Hi, thanks for your feedback.

Regarding your question with the Enchanting extension. You can put books or bookshelves in one of the solts to increase the enchantment level. You need the same number of bookshelves as when you normally "build" it. 

Regarding the bug, yes I am aware of this but unfortunately there is not much I can do about it as this functionality is provided by Minecraft vanilla and is unfortunately designed for smaller containers. I will increase the performance with the next update, but I can't guarantee this.

I hope this is helpful, I will let you know if I have improved anything

**Comment by Aetrnl94** [comment]
That's exactly what I was hoping to hear! So far, out of the 121 mods I have installed, yours is my absolute favorite, as it enables me to be the hoarder I want to be from the get-go! I appreciate your work and look forward to your next update!

**Comment by Luis-St** [comment]
Hi,
a few minutes ago I released version 3.3 on CurseForge. In this version I tried to improve the performance when putting items into the backpack, by replacing the vanilla minecraft logic here. Please note that this is a beta release as I could not yet test the functionality of my changes 100% (e.g. the behaviour with a completely full backpack). 

It should also be noted that I could not really test the changes on my PC for performace, as I had a high-end CPU (I9-13th gen) and this was not really a problem before. Which is why I am very curious about your feedback.

**Comment by Luis-St** [comment]
Due to lack of feedback I will close this issue.
Feel free to open a new one.
